/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COMMONAPI_CAN_STUB_HPP_
#define V1_COMMONAPI_CAN_STUB_HPP_

#include <functional>
#include <sstream>




#include <v1/commonapi/CAN.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#include <mutex>

#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service CAN. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class CANStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual CAN {
 public:
    ///Notifies all remote listeners about a change of value of the attribute hum.
    virtual void fireHumAttributeChanged(const uint8_t &hum) = 0;
    ///Notifies all remote listeners about a change of value of the attribute tmp.
    virtual void fireTmpAttributeChanged(const int8_t &tmp) = 0;
    ///Notifies all remote listeners about a change of value of the attribute rpm.
    virtual void fireRpmAttributeChanged(const uint16_t &rpm) = 0;
    ///Notifies all remote listeners about a change of value of the attribute spd.
    virtual void fireSpdAttributeChanged(const uint8_t &spd) = 0;
    ///Notifies all remote listeners about a change of value of the attribute bat.
    virtual void fireBatAttributeChanged(const uint8_t &bat) = 0;


    virtual void deactivateManagedInstances() = 0;

    void lockHumAttribute(bool _lockAccess) {
        if (_lockAccess) {
            humMutex_.lock();
        } else {
            humMutex_.unlock();
        }
    }
    void lockTmpAttribute(bool _lockAccess) {
        if (_lockAccess) {
            tmpMutex_.lock();
        } else {
            tmpMutex_.unlock();
        }
    }
    void lockRpmAttribute(bool _lockAccess) {
        if (_lockAccess) {
            rpmMutex_.lock();
        } else {
            rpmMutex_.unlock();
        }
    }
    void lockSpdAttribute(bool _lockAccess) {
        if (_lockAccess) {
            spdMutex_.lock();
        } else {
            spdMutex_.unlock();
        }
    }
    void lockBatAttribute(bool _lockAccess) {
        if (_lockAccess) {
            batMutex_.lock();
        } else {
            batMutex_.unlock();
        }
    }

protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */
    std::recursive_mutex humMutex_;
    std::recursive_mutex tmpMutex_;
    std::recursive_mutex rpmMutex_;
    std::recursive_mutex spdMutex_;
    std::recursive_mutex batMutex_;

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for CAN.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class CANStubRemoteEvent
{
public:
    virtual ~CANStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service CAN to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class CANStub
    : public virtual CommonAPI::Stub<CANStubAdapter, CANStubRemoteEvent>
{
public:

    virtual ~CANStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 5);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// Provides getter access to the attribute hum
    virtual const uint8_t &getHumAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireHumAttributeChanged(uint8_t _value) {
    auto stubAdapter = CommonAPI::Stub<CANStubAdapter, CANStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireHumAttributeChanged(_value);
    }
    void lockHumAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<CANStubAdapter, CANStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockHumAttribute(_lockAccess);
    }
    /// Provides getter access to the attribute tmp
    virtual const int8_t &getTmpAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireTmpAttributeChanged(int8_t _value) {
    auto stubAdapter = CommonAPI::Stub<CANStubAdapter, CANStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireTmpAttributeChanged(_value);
    }
    void lockTmpAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<CANStubAdapter, CANStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockTmpAttribute(_lockAccess);
    }
    /// Provides getter access to the attribute rpm
    virtual const uint16_t &getRpmAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireRpmAttributeChanged(uint16_t _value) {
    auto stubAdapter = CommonAPI::Stub<CANStubAdapter, CANStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireRpmAttributeChanged(_value);
    }
    void lockRpmAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<CANStubAdapter, CANStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockRpmAttribute(_lockAccess);
    }
    /// Provides getter access to the attribute spd
    virtual const uint8_t &getSpdAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireSpdAttributeChanged(uint8_t _value) {
    auto stubAdapter = CommonAPI::Stub<CANStubAdapter, CANStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireSpdAttributeChanged(_value);
    }
    void lockSpdAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<CANStubAdapter, CANStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockSpdAttribute(_lockAccess);
    }
    /// Provides getter access to the attribute bat
    virtual const uint8_t &getBatAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireBatAttributeChanged(uint8_t _value) {
    auto stubAdapter = CommonAPI::Stub<CANStubAdapter, CANStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireBatAttributeChanged(_value);
    }
    void lockBatAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<CANStubAdapter, CANStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockBatAttribute(_lockAccess);
    }


    using CommonAPI::Stub<CANStubAdapter, CANStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<CANStubAdapter, CANStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<CANStubAdapter, CANStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef CANStubRemoteEvent RemoteEventType;
    typedef CAN StubInterface;
};

} // namespace commonapi
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_CAN_STUB_HPP_
